"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import SessionWrapper from "./components/SessionWrapper";
import store from "@/redux/store";
import { Provider } from "react-redux";

// import { Provider } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        <Provider store={store}>

          <SessionWrapper>
            <Navbar />
            {children}
            <Footer />
          </SessionWrapper>
          </Provider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
